<script setup>
import { defineEmits } from 'vue'

const emit = defineEmits(['dismiss'])

function handleDismiss() {
  emit('dismiss')
}
</script>

<template>
  <div class="disclaimer-overlay" @click="handleDismiss">
    <div class="disclaimer-modal" @click.stop>
      <div class="modal-header">
        <span class="warning-icon">⚠️</span>
        <h1 class="modal-title">Disclaimer</h1>
      </div>
      
      <div class="modal-content">
        <p class="main-warning">
          Everything you see, read, or experience here is <strong>100% AI generated</strong>.
        </p>
        
        <div class="details">
          <p>This entire application was created through agentic software engineering:</p>
          <ul>
            <li>All code was generated by AI agents</li>
            <li>All content is AI-created</li>
            <li>All design decisions were made with AI assistance</li>
          </ul>
        </div>
        
        <p class="footnote">
          This is an experimental demonstration. Use at your own discretion.
        </p>
      </div>
      
      <div class="modal-actions">
        <button class="dismiss-btn" @click="handleDismiss">
          I Understand
        </button>
      </div>
    </div>
  </div>
</template>

<style scoped>
.disclaimer-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.8);
  backdrop-filter: blur(10px);
  -webkit-backdrop-filter: blur(10px);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 10000;
  padding: var(--space-4);
  animation: fadeIn 0.3s ease-out;
}

@keyframes fadeIn {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

.disclaimer-modal {
  background: var(--bg-primary);
  border: 2px solid #eab308;
  border-radius: var(--radius-xl);
  max-width: 600px;
  width: 100%;
  padding: var(--space-8);
  box-shadow: 
    0 20px 60px rgba(0, 0, 0, 0.5),
    0 0 0 1px rgba(234, 179, 8, 0.2);
  animation: slideUp 0.3s ease-out;
}

@keyframes slideUp {
  from {
    transform: translateY(50px);
    opacity: 0;
  }
  to {
    transform: translateY(0);
    opacity: 1;
  }
}

.modal-header {
  display: flex;
  align-items: center;
  gap: var(--space-3);
  margin-bottom: var(--space-6);
  padding-bottom: var(--space-4);
  border-bottom: 1px solid var(--border-default);
}

.warning-icon {
  font-size: 3rem;
  animation: pulse 2s ease-in-out infinite;
}

@keyframes pulse {
  0%, 100% {
    transform: scale(1);
  }
  50% {
    transform: scale(1.1);
  }
}

.modal-title {
  font-size: var(--text-3xl);
  font-weight: var(--font-bold);
  color: #eab308;
  margin: 0;
  font-family: var(--font-mono);
}

.modal-content {
  display: flex;
  flex-direction: column;
  gap: var(--space-5);
  margin-bottom: var(--space-6);
}

.main-warning {
  font-size: var(--text-xl);
  line-height: 1.6;
  color: var(--text-primary);
  margin: 0;
  padding: var(--space-4);
  background: rgba(234, 179, 8, 0.1);
  border-left: 4px solid #eab308;
  border-radius: var(--radius-md);
}

.main-warning strong {
  color: #eab308;
  font-weight: var(--font-bold);
}

.details {
  display: flex;
  flex-direction: column;
  gap: var(--space-3);
}

.details p {
  margin: 0;
  color: var(--text-secondary);
  font-size: var(--text-base);
}

.details ul {
  list-style: none;
  padding: 0;
  margin: 0;
  display: flex;
  flex-direction: column;
  gap: var(--space-2);
}

.details li {
  padding: var(--space-2) var(--space-3);
  background: var(--bg-secondary);
  border-radius: var(--radius-md);
  color: var(--text-secondary);
  font-size: var(--text-sm);
  position: relative;
  padding-left: var(--space-6);
}

.details li::before {
  content: '▸';
  position: absolute;
  left: var(--space-3);
  color: #eab308;
  font-weight: var(--font-bold);
}

.footnote {
  margin: 0;
  font-size: var(--text-sm);
  color: var(--text-tertiary);
  font-style: italic;
  text-align: center;
}

.modal-actions {
  display: flex;
  justify-content: center;
  padding-top: var(--space-4);
  border-top: 1px solid var(--border-default);
}

.dismiss-btn {
  padding: var(--space-4) var(--space-8);
  background: linear-gradient(135deg, #eab308 0%, #ca8a04 100%);
  border: none;
  border-radius: var(--radius-lg);
  color: #000;
  font-size: var(--text-lg);
  font-weight: var(--font-bold);
  cursor: pointer;
  transition: all var(--duration-fast);
  box-shadow: 0 4px 12px rgba(234, 179, 8, 0.3);
}

.dismiss-btn:hover {
  transform: translateY(-2px);
  box-shadow: 0 8px 24px rgba(234, 179, 8, 0.5);
  background: linear-gradient(135deg, #fbbf24 0%, #eab308 100%);
}

.dismiss-btn:active {
  transform: translateY(0);
}

/* Responsive */
@media (max-width: 768px) {
  .disclaimer-modal {
    padding: var(--space-6);
  }

  .modal-header {
    flex-direction: column;
    text-align: center;
  }

  .warning-icon {
    font-size: 2.5rem;
  }

  .modal-title {
    font-size: var(--text-2xl);
  }

  .main-warning {
    font-size: var(--text-lg);
  }

  .dismiss-btn {
    width: 100%;
  }
}
</style>
