source 'https://rubygems.org'

gem 'sinatra', '~> 3.0'
gem 'sinatra-cors', '~> 1.2'
gem 'puma', '~> 6.0'
gem 'faye-websocket', '~> 0.11'
gem 'json', '~> 2.6'
gem 'rackup', '~> 1.0'
gem 'rack', '~> 2.2'
